### ISSUE TITLE
Haxe3 migration

### ISSUE THREAD

**Issue by JbIPS** [clemos/haxe-bootstrap#1]
I tried to use it with haxe-3.0.0 compiler and get:
`haxe-bootstrap/bootstrap/Lib.hx:6: Macro classes are no longer allowed in haxe 3`

Any idea on how to replace `@:macro class Lib` ?

**Comment by clemos** [comment]
I believe you can just remove @:macro
And add "macro" in front of the two classes.
You can add conditionnals (#if !haxe3 #if haxe3) to keep it backwards
compatible.

**Comment by JbIPS** [comment]
That worked. I sent a pull request that fix that
