### ISSUE TITLE
Help to start

### ISSUE THREAD

**Issue by JbIPS** [clemos/haxe-bootstrap#3]
I'm having some troubles to start with the lib.

Here my code: 

``` haxe
package;
import js.Lib;
import js.JQuery;
import js.Browser;
using js.bootstrap.Button;

class TestBootStrap {
    private var myButton:JQuery;

    public function new () {
        initialize ();
    }

    private function initialize () {
        myButton = new JQuery("button").buttonLoading();
    }

    static function main () {
        new TestBootStrap ();
    }
}
```

In my HTML, I put `<button type="button" class="btn" data-loading-text="loading stuff...">...</button>`.

Nothing happens, I'm clearly missing something, but what...

**Comment by clemos** [comment]
I belive you might need to initialize it in the first place, using
`new JQuery("button").button()` ...before `.buttonLoading()`

You should try to debug this through Chrome Developer Tools or Firebug console, trying to see if just typing `$("button").button('loading')` works.
BTW do you receive any error in the console ?

**Comment by JbIPS** [comment]
I updated my initialize function to:

``` haxe
 new JQuery(".btn").button();
 myButton = new JQuery(".btn").button('loading');
```

and Firebug showed me this error: `TypeError: $ is undefined in var old = $.fn.button`

This happens here in my js file:

``` javascript
/* BUTTON PLUGIN DEFINITION
* ======================== */
var old = $.fn.button 
```

**Comment by clemos** [comment]
You need to include JQuery, dude...

**Comment by JbIPS** [comment]
In the JS file ? Doesn't `import js.JQuery;` in the Haxe file do the trick ?

**Comment by clemos** [comment]
I think the most reliable way is just to include jquery manually
(eventually from Google CDN) using a <script> tag.
I don't know the current status of Haxe's js.JQuery regarding this, but I
believe it has changed in Haxe3 (no injection by default)

**Comment by JbIPS** [comment]
I added 

``` html
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
```

before my own script tag but the error's still here.

Thanks for your help, I'm kind of a noob with JS.

**Comment by clemos** [comment]
I believe bootstrap is not compatible with JQuery 2.x series (
https://github.com/twitter/bootstrap/issues/7627)
You'll need to include 1.9.1 or something

**Comment by clemos** [comment]
BTW you don't need JQuery UI I think

**Comment by JbIPS** [comment]
One stupid error between the chair and the keyboard: Google CDN link doesn't have `http:`. Once I added it, it worked.
Here's my starter code for future beginners:

``` haxe
package;
import js.Lib;
import js.JQuery;
import js.Browser;
using js.bootstrap.Button;

class TestBootStrap {
    private var myButton:JQuery;

    public function new(){
        initialize();
    }

    private function initialize(){
        new JQuery("button").button();
        myButton = new JQuery("button");
        myButton.click(function(e){
            Lib.alert("ok");
            myButton.button('complete');
        });
    }

    static function main(){
        new JQuery (Browser.document.head).ready(function(evt){
            new TestBootStrap ();
        });
    }
}
```

With this HTML button  

``` html
<button type="button" class="btn" data-complete-text="finished!">...</button>
```

**Comment by clemos** [comment]
It's really weird because "//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js" should work.
Omitting "http:" is actually valid, it's intended to make the same link work both in http and https...
Well, it seems to work anyway, so nevermind ;)
